# 05 · Previsão

Atualiza a série com os focos de 2026 (até agosto) e prevê os meses seguintes.

In [1]:
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

import sys; sys.path.append("..")
from src import climate_loader, data_loader, features, models

In [7]:
historico = pd.read_csv("../data/processed/focos_mensais.csv", parse_dates=["mes"])
recentes = data_loader.load_recent(Path("../data/raw/2026"))
mensal_2026 = features.monthly_counts(recentes)

monthly = pd.concat([historico, mensal_2026], ignore_index=True)
monthly.groupby("bioma")["mes"].agg(["min", "max"])

                min        max
bioma
Amazônia 2015-01-01 2026-08-01
Cerrado  2015-01-01 2026-08-01
Pantanal 2015-01-01 2026-08-01

In [8]:
clima = climate_loader.load_climate(2015, 2026)
clima.groupby("bioma")["mes"].agg(["min", "max"])

                min        max
bioma
Amazônia 2015-01-01 2026-08-01
Cerrado  2015-01-01 2026-08-01
Pantanal 2015-01-01 2026-08-01